In [1]:
import numpy as np

# NumPy: matrix ops, broadcasting

In [5]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

## Basic Arithmetic Operations - addition

In [7]:
a + b, np.add(a, b)

(array([[ 6,  8],
        [10, 12]]),
 array([[ 6,  8],
        [10, 12]]))

## Basic Arithmetic Operations - substraction

In [9]:
a - b, np.subtract(a, b)

(array([[-4, -4],
        [-4, -4]]),
 array([[-4, -4],
        [-4, -4]]))

## Basic Arithmetic Operations - multiplication

In [10]:
a * b, np.multiply(a, b)

(array([[ 5, 12],
        [21, 32]]),
 array([[ 5, 12],
        [21, 32]]))

## Basic Arithmetic Operations - division

In [11]:
a / b, np.divide(a, b)

(array([[0.2       , 0.33333333],
        [0.42857143, 0.5       ]]),
 array([[0.2       , 0.33333333],
        [0.42857143, 0.5       ]]))

## Scalar Multiplication

In [13]:
a * 4, b * 10

(array([[ 4,  8],
        [12, 16]]),
 array([[50, 60],
        [70, 80]]))

## Matrix Multiplication - Dot Product

In [15]:
a @ b, np.dot(a, b)

(array([[19, 22],
        [43, 50]]),
 array([[19, 22],
        [43, 50]]))

## Matrix Multiplication - Matric Product

In [16]:
np.matmul(a, b)

array([[19, 22],
       [43, 50]])

## Transpose

In [18]:
a.T, b.T

(array([[1, 3],
        [2, 4]]),
 array([[5, 7],
        [6, 8]]))

## Determinant

In [19]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

## Inverse

In [20]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## Flatten or Ravel

In [23]:
a.flatten(), a.ravel()

(array([1, 2, 3, 4]), array([1, 2, 3, 4]))

## Broadcasting

In [24]:
a = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
b = np.array([10, 20, 30])           # Shape (3,)

# Broadcasting applies:
# 1. Pad b's shape: (3,) becomes (1, 3)
# 2. Match dimensions:
#    - Rightmost dimension: 3 and 3 are equal.
#    - Leftmost dimension: 2 and 1. The 1 in (1, 3) is stretched to 2.
# Resulting effective shapes for operation: (2, 3) and (2, 3)

result = a + b
print(result)

[[11 22 33]
 [14 25 36]]
